// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GlobalLoading: typeof import('./src/components/GlobalLoading/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MobComp: typeof import('./src/components/TopBar/MobComp.vue')['default']
    PCComp: typeof import('./src/components/TopBar/PCComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/TopBar/index.vue')['default']
    TopBarOld: typeof import('./src/components/TopBar-old.vue')['default']
  }
}
